### ISSUE TITLE
Build Requirements and instructions

### ISSUE THREAD

**Issue by rmccullagh** [0X1A/mpm#1]
I think it would be useful to have dependencies and installation information in the docs. For users to be able to compile and install the executable such as myself.

**Comment by 0X1A** [comment]
@rmccullagh Yeah, things are a little poorly documented right now because I'm still going through the process of deciding how to define the schema for a package. As of right now mpm doesn't install anything to the local file system, did you mean build instructions? Doesn't require anything special other than cargo and rustc

**Comment by rmccullagh** [comment]
+1
